// Generated by cargo run --bin gen-api-types. Do not edit.
/* oxlint-disable typescript-eslint/array-type */

export type VaultEntry = { index: number, name: string, };

export type NoteMeta = { noteId: string, path: string, title: string, tags: Array<string>, seq: number, contentHash: string, updatedAtMs: number, };

export type NoteDocument = { meta: NoteMeta, content: string, };

export type RevisionMeta = { eventId: number, noteId: string, seq: number, kind: NoteEventKind, source: NoteEventSource, contentHash: string | null, createdAtMs: number, };

export type RevisionDocument = { revision: RevisionMeta, content: string, };

export type NoteEventKind = "baseline" | "create" | "import" | "save" | "rename" | "delete" | "external_edit" | "external_rename" | "external_delete" | "conflict_recovery";

export type NoteEventSource = "user" | "import" | "external" | "repair";

export type ConflictDraftMeta = { draftId: number, noteId: string, baseSeq: number, baseHash: string, contentHash: string, createdAtMs: number, };

export type ConflictDraftDocument = { draft: ConflictDraftMeta, content: string, };

export type Settings = { excludedFolders: Array<string>, searchTitleWeight: number, searchHeadingWeight: number, searchTagWeight: number, searchContentWeight: number, recencyBoost: number, autosaveDelayMs: number, undoStackMax: number, imageWebpQuality: number, };

export type SessionState = { openTabs: Array<SessionTab>, activeNoteId: string | null, closedTabs: Array<SessionTab>, };

export type SessionTab = { noteId: string, title: string, path: string, cursorOffset: number | null, sourceMode: boolean, };

export type SearchStatus = { dirty: boolean, degraded: boolean, };

export type SearchFieldScores = { title: number, headings: number, tags: number, content: number, };

export type SearchHit = { note: NoteMeta, snippet: string, score: number, fieldScores: SearchFieldScores, };

export type BootstrapResponse = { apiVersion: number, vaults: Array<VaultEntry>, activeVault: number, notes: Array<NoteMeta>, pinnedNoteIds: Array<string>, recentNoteIds: Array<string>, settings: Settings, session: SessionState, searchStatus: SearchStatus, };

export type ServerEvent = { kind: ServerEventKind, vault: number, notes: Array<NoteMeta>, deletedNoteIds: Array<string>, searchStatus: SearchStatus, };

export type ServerEventKind = "ready" | "vault_changed" | "note_changed" | "note_deleted" | "search_changed";

export type CreateNoteRequest = { path: string, content: string, source: NoteEventSource | null, };

export type SaveNoteRequest = { content: string, baseSeq: number, baseHash: string, checkpoint: boolean | null, };

export type RenameNoteRequest = { path: string, };

export type NoteMutationResponse = { document: NoteDocument | null, meta: NoteMeta, syncVersion: number, };

export type ImageUploadResponse = { name: string, markdown: string, };

export type ApiErrorResponse = { error: ApiErrorKind, };

export type ApiErrorKind = { "code": "path_invalid", reason: PathValidationReason, } | { "code": "path_collision", path: string, } | { "code": "note_not_found", note_id: string, } | { "code": "save_conflict", current: NoteDocument, draft: ConflictDraftMeta, } | { "code": "unresolved_note", note_id: string, reason: UnresolvedReason, } | { "code": "bad_request", message: string, } | { "code": "internal", message: string, };

export type PathValidationReason = "empty" | "absolute" | "traversal" | "dot_tansu" | "not_markdown" | "nested_vault";

export type UnresolvedReason = "case_fold_collision" | "invalid_utf8" | "missing_snapshot" | "corrupt_snapshot" | "file_catalog_mismatch";

